### ISSUE TITLE
Absence of liste_patienten.csv

### ISSUE THREAD

**Issue by ghost** [CrazyBigFoot/mimic3#50]
Hi, thank you for your meticulous repo describing MIMIC-III.

I wanna run your code from **0. Overview-data.ipynb**, but i don't know how to obtain to it. Do you mind sharing the file? Thanks!

**Comment by m-kno** [comment]
Hi,
unfortunately, we are not allowed to make the raw data public. However, the data is available if you get certified. More info at: https://mimic.mit.edu/docs/
Thanks for the request
